version: "3"
services:
    db:
        image: mysql:5.7.28
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: 'Asia/Tokyo'
        volumes:
            - ./docker:/docker-entrypoint-initdb.d
